### ISSUE TITLE
name is not recordnised

### ISSUE THREAD

**Issue by philsniff** [magtimmermans/com.cyclone-software.fbcallmonitor#1]
i called myself from mobil at home. the number is correct spoken by homey. but the name ist something like "corrosponding name under ..." ?

**Comment by philsniff** [comment]
i just created an applet with the new ifttt-app and let mail the name of the caller to me, so i can say what homey says:

fb_abonnee_name (home says: "fb underscore abonnee underscore name"

so i think the variable isn't correct mentoined.

my mailtext from ifttt:

"anruf zu hause" (ifttt-name) has run on Homey at November 19, 2016 at 04:27 PM with dara: [[fb_abonnee_name]]

hope it helps
:-)

**Comment by magtimmermans** [comment]
Is fixed. Please make sure the number is exactly the same as in the phonebook.
