### ISSUE TITLE
Update to Homey Pro (Early 2023)

### ISSUE THREAD

**Issue by chiroptera-git** [magtimmermans/com.cyclone-software.fbcallmonitor#10]
I would like you to update the App to work with Homey Pro (Early 2023). Seems that even the Git repository is not updated for a long time. Do you mind to upload the v0.2.4 files?

**Comment by magtimmermans** [comment]
https://tools.developer.homey.app/apps/app/com.cyclone-software.fbcallmonitor/build/2
Done!
