### ISSUE TITLE
Can you please add Thermostate and other DECT ULE Devices.

### ISSUE THREAD

**Issue by m-holler** [magtimmermans/com.cyclone-software.fbcallmonitor#4]
Would be great if you can add this new funktions to your app.
Outside it is cold now so it´s time to update. :-)

**Comment by magtimmermans** [comment]
Hi, that part of the app I didn't make it and I have no devices to test. I am upgrading to sdk 2. But also the dect devices are not working. Probably I will remove that part completely as the developer does not respond 😟
