### ISSUE TITLE
homey v2 ready

### ISSUE THREAD

**Issue by satbopper** [magtimmermans/com.cyclone-software.fbcallmonitor#5]
I think it is not homey v2 proof
yes or no and will you develop this further

**Comment by magtimmermans** [comment]
Well, I have the part that I have original written V2 compliant. But the part that is written by a third party developer is not converted (regarding Smart Home Devices). Unfortunately, the developer doesn't respond on my request and I do not have the equipment to test etc. So I am thinking to release without this.

**Comment by satbopper** [comment]
ok thanks yes because it is a usefull app
also thanks for the message and ik hou het in de gaten hi,kunnen we testen onder v2

**Comment by magtimmermans** [comment]
rewrite is done
