### ISSUE TITLE
How to add phonebook manually?

### ISSUE THREAD

**Issue by jeesnl** [magtimmermans/com.cyclone-software.fbcallmonitor#6]
My fritzbox 7340 cannot export the phonebook. Is there a posibility to add it manually?

**Comment by magtimmermans** [comment]
You could create the xml structure by hand and then past it in.

**Comment by jeesnl** [comment]
Hi Mag,

What structure should it have? Do you have an example?

Verstuurd vanaf mijn iPad

**Comment by magtimmermans** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<phonebooks>
   <phonebook>
      <contact>
         <category />
         <person>
            <realName>Naam 1</realName>
         </person>
         <telephony nid="1">
            <number type="home" prio="1" id="0">01234567890</number>
         </telephony>
         <services />
         <setup />
         <mod_time>1388844962</mod_time>
         <uniqueid>1</uniqueid>
      </contact>
      <contact>
         <category />
         <person>
            <realName>Naam 2</realName>
         </person>
         <telephony nid="1">
            <number type="home" prio="1" id="0">1234333321</number>
         </telephony>
         <services />
         <setup />
         <mod_time>1388844962</mod_time>
         <uniqueid>2</uniqueid>
      </contact>
       <contact>
         <category />
         <person>
            <realName>Naam 3</realName>
         </person>
         <telephony nid="1">
            <number type="home" prio="1" id="0">02012345678</number>
         </telephony>
         <services />
         <setup />
         <mod_time>1388844962</mod_time>
         <uniqueid>3</uniqueid>
      </contact>
  </phonebook>
</phonebooks>

**Comment by magtimmermans** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<phonebooks>
   <phonebook>
      <contact>
         <category />
         <person>
            <realName>Naam 1</realName>
         </person>
         <telephony nid="1">
            <number type="home" prio="1" id="0">01234567890</number>
         </telephony>
         <services />
         <setup />
         <mod_time>1388844962</mod_time>
         <uniqueid>1</uniqueid>
      </contact>
      <contact>
         <category />
         <person>
            <realName>Naam 2</realName>
         </person>
         <telephony nid="1">
            <number type="home" prio="1" id="0">1234333321</number>
         </telephony>
         <services />
         <setup />
         <mod_time>1388844962</mod_time>
         <uniqueid>2</uniqueid>
      </contact>
       <contact>
         <category />
         <person>
            <realName>Naam 3</realName>
         </person>
         <telephony nid="1">
            <number type="home" prio="1" id="0">02012345678</number>
         </telephony>
         <services />
         <setup />
         <mod_time>1388844962</mod_time>
         <uniqueid>3</uniqueid>
      </contact>
  </phonebook>
</phonebooks>`

**Comment by magtimmermans** [comment]
When you put this in online https://www.freeformatter.com then the file will be nicely formatted and more readable. Basically the contact block you can copy every time. Change the name and the number and make a unique id.
