### ISSUE TITLE
Support for DECT smart plugs

### ISSUE THREAD

**Issue by MischaKluin** [magtimmermans/com.cyclone-software.fbcallmonitor#7]
Hi Marcel,

I have read you were not able to support the DECT 200 smart plugs anymore in v0.2.0 ,
as you do not own one of these. 
I have some Fritz!plugs available. Would you like me to send you one?

**Comment by magtimmermans** [comment]
Hi, not needed as this should be in a different app. I am not very familiar with this and at the moment i have no time.
